"""Minimal dependency-free constants shared across the process boundary."""

ANALYSIS_SCHEMA_VERSION = "2.1"
API_SCHEMA_VERSION = "1.3"
WORKER_VERSION = "0.8.0"

MAX_FINDINGS_PER_ANALYSIS = 256
MAX_FINDING_METADATA_BYTES = 16 * 1024
MAX_ANALYZER_METADATA_BYTES = 32 * 1024

__all__ = [
    "ANALYSIS_SCHEMA_VERSION",
    "API_SCHEMA_VERSION",
    "MAX_ANALYZER_METADATA_BYTES",
    "MAX_FINDINGS_PER_ANALYSIS",
    "MAX_FINDING_METADATA_BYTES",
    "WORKER_VERSION",
]
