"""Worker-only dependency and parser configuration constants."""

PDF_PARSER_NAME = "pikepdf"
PDF_PARSER_VERSION = "10.11.0"
PDF_ENGINE_VERSION = "12.3.2"
OFFICE_VBA_PARSER_NAME = "oletools"
OFFICE_VBA_PARSER_VERSION = "0.60.2"
OFFICE_OLE_PARSER_NAME = "olefile"
OFFICE_OLE_PARSER_VERSION = "0.47"
OFFICE_XML_PARSER_NAME = "defusedxml"
OFFICE_XML_PARSER_VERSION = "0.7.1"
OFFICE_PYPARSING_VERSION = "3.2.5"
YARA_PYTHON_VERSION = "4.5.4"
YARA_RUNTIME_VERSION = "4.5.4"

__all__ = [
    "OFFICE_OLE_PARSER_NAME",
    "OFFICE_OLE_PARSER_VERSION",
    "OFFICE_PYPARSING_VERSION",
    "OFFICE_VBA_PARSER_NAME",
    "OFFICE_VBA_PARSER_VERSION",
    "OFFICE_XML_PARSER_NAME",
    "OFFICE_XML_PARSER_VERSION",
    "PDF_ENGINE_VERSION",
    "PDF_PARSER_NAME",
    "PDF_PARSER_VERSION",
    "YARA_PYTHON_VERSION",
    "YARA_RUNTIME_VERSION",
]
