"""Security-sensitive constants shared across trusted components."""

from docguard_contract import (
    ANALYSIS_SCHEMA_VERSION as ANALYSIS_SCHEMA_VERSION,
)
from docguard_contract import (
    WORKER_VERSION as WORKER_VERSION,
)

DEFAULT_MAX_UPLOAD_BYTES = 25 * 1024 * 1024
DEFAULT_WORKER_TIMEOUT_SECONDS = 10.0
DEFAULT_WORKER_STDOUT_MAX_BYTES = 256 * 1024
DEFAULT_WORKER_STDERR_MAX_BYTES = 64 * 1024
DEFAULT_WORKER_MEMORY_LIMIT_BYTES = 512 * 1024 * 1024
DEFAULT_WORKER_FILE_SIZE_LIMIT_BYTES = 64 * 1024 * 1024
DEFAULT_WORKER_OPEN_FILES_LIMIT = 64
DEFAULT_WORKER_TASKS_LIMIT = 32
DEFAULT_WORKER_CPU_LIMIT_SECONDS = 8
DEFAULT_WORKER_TMPFS_BYTES = 64 * 1024 * 1024
DEFAULT_CDR_TIMEOUT_SECONDS = 30.0
OPAQUE_STORAGE_KEY_BYTES = 16
SESSION_TOKEN_BYTES = 32
CSRF_CONTEXT = b"docguard-csrf-v1"
DEFAULT_SESSION_ABSOLUTE_SECONDS = 8 * 60 * 60
DEFAULT_SESSION_INACTIVITY_SECONDS = 30 * 60
DEFAULT_SESSION_REFRESH_SECONDS = 5 * 60
DEFAULT_LOGIN_ATTEMPTS_PER_MINUTE = 5
DEFAULT_LOGIN_ATTEMPTS_PER_HOUR = 50
DEFAULT_LIST_PAGE_SIZE = 25
MAX_LIST_PAGE_SIZE = 100
DEFAULT_UPLOADS_PER_HOUR = 60
DEFAULT_CDR_REQUESTS_PER_HOUR = 20
DEFAULT_ARTIFACT_DOWNLOADS_PER_HOUR = 200
DEFAULT_EXPENSIVE_READS_PER_MINUTE = 300
DEFAULT_SQLITE_BUSY_TIMEOUT_MS = 5_000
DEFAULT_RECONCILIATION_STALE_SECONDS = 15 * 60
REQUEST_ID_BYTES = 16
